package com.agenciahub.api.application.controller;

import com.agenciahub.api.application.persistence.entity.*;
import com.agenciahub.api.application.persistence.repository.*;
import com.agenciahub.api.domain.*;
import com.agenciahub.api.exception.ResourceNotFoundException;
import com.agenciahub.api.security.TenantContext;
import jakarta.transaction.Transactional;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.math.*;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/** Registros comerciais. Somente a quitação de uma conta cria movimento de caixa. */
@RestController @RequestMapping("/sales") @PreAuthorize("hasRole('AGENCY_OWNER')") @RequiredArgsConstructor
public class SaleController {
 private static final BigDecimal ZERO=BigDecimal.ZERO;
 private final SaleRepository sales; private final AgencyRepository agencies; private final CrmCustomerRepository customers; private final QuotationRepository quotations; private final SupplierRepository suppliers; private final PlatformAccountRepository users; private final SaleItemRepository items; private final ReceivableRepository receivables; private final PayableRepository payables; private final SaleCommissionRepository commissions; private final FinancialEntryRepository financialEntries;

 @GetMapping @Transactional public List<SaleSummary> list(@RequestParam(required=false) UUID customerId){UUID a=TenantContext.requireAgencyId();return (customerId==null?sales.findAllByAgency_IdOrderBySaleDateDesc(a):sales.findAllByAgency_IdAndCustomer_IdOrderBySaleDateDesc(a,customerId)).stream().map(SaleSummary::from).toList();}
 /** Comissões de venda do próprio usuário autenticado (gestor ou vendedor) — nunca de outro. */
 @GetMapping("/commissions/mine") @PreAuthorize("hasAnyRole('AGENCY_OWNER','SALES_AGENT')") @Transactional public List<MyCommission> myCommissions(@AuthenticationPrincipal PlatformAccount caller){return payables.findByCommissionRecipientUser_IdAndPayableTypeOrderByDueDateDesc(caller.getId(),"COMMISSION").stream().map(MyCommission::from).toList();}
 @GetMapping("/{id}") @Transactional public SaleDetails get(@PathVariable UUID id){Sale s=find(id);return SaleDetails.from(s,items.findBySale_Id(id),receivables.findBySale_Id(id),payables.findBySale_Id(id),commissions.findBySale_Id(id));}

 @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional public SaleSummary create(@Valid @RequestBody CreateSale r){
  UUID a=TenantContext.requireAgencyId(); CrmCustomer customer=customers.findByIdAndAgency_Id(r.customerId(),a).orElseThrow(()->new ResourceNotFoundException("cliente não encontrado")); validateTotals(r);
  Quotation quotation=r.quotationId()==null?null:quotations.findByIdAndAgency_Id(r.quotationId(),a).orElseThrow(()->new ResourceNotFoundException("cotação não encontrada"));if(quotation!=null&&!customer.getId().equals(quotation.getCustomer().getId()))throw new IllegalArgumentException("A cotação deve pertencer ao cliente da venda"); Sale sale=sales.save(Sale.builder().agency(agencies.getReferenceById(a)).customer(customer).quotation(quotation).totalAmount(r.totalAmount()).saleDate(r.saleDate()).status("OPEN").recurrenceFrequency(r.recurrenceFrequency()).notes(r.notes()==null?"":r.notes().strip()).build());
  for(Item i:safe(r.items())){Supplier supplier=supplier(i.supplierId(),a); SaleItem item=items.save(SaleItem.builder().sale(sale).supplier(supplier).description(i.description().strip()).itemType(blankOr(i.itemType(),"OTHER")).saleAmount(i.saleAmount()).supplierCost(i.supplierCost()).customerPaysSupplierDirectly(Boolean.TRUE.equals(i.customerPaysSupplierDirectly())).build()); if(item.getSupplierCost()!=null&&item.getSupplierCost().signum()>0)payables.save(Payable.builder().sale(sale).supplier(supplier).payableType("SUPPLIER").amount(item.getSupplierCost()).dueDate(i.dueDate()).status("PENDING").build());}
  for(Installment i:safe(r.receivables()))receivables.save(Receivable.builder().sale(sale).installmentNumber(i.number()).amount(i.amount()).dueDate(i.dueDate()).paymentMethod(i.paymentMethod()).bankAccount(i.bankAccount()).status("PENDING").build());
  for(Commission c:safe(r.commissions())){PlatformAccount recipient=users.findByIdWithAgency(c.recipientUserId()).orElseThrow(()->new ResourceNotFoundException("beneficiário não encontrado"));if(recipient.getAgency()==null||!a.equals(recipient.getAgency().getId()))throw new IllegalArgumentException("beneficiário não pertence à agência"); BigDecimal amount=commissionAmount(c,r.totalAmount());commissions.save(SaleCommission.builder().sale(sale).recipientUser(recipient).calculationType(c.calculationType()).calculationValue(c.calculationValue()).amount(amount).build());payables.save(Payable.builder().sale(sale).commissionRecipientUser(recipient).payableType("COMMISSION").amount(amount).dueDate(c.dueDate()).status("PENDING").build());}
  return SaleSummary.from(sale);
 }

 @PostMapping("/receivables/{id}/settle") @Transactional public void settleReceivable(@PathVariable UUID id,@RequestBody Settle r){Receivable receivable=receivables.findById(id).orElseThrow(()->new ResourceNotFoundException("recebimento não encontrado"));assertAgency(receivable.getSale());if("PAID".equals(receivable.getStatus()))throw new IllegalArgumentException("Recebimento já quitado");FinancialEntry e=financialEntries.save(FinancialEntry.builder().agency(receivable.getSale().getAgency()).customer(receivable.getSale().getCustomer()).description("Recebimento de venda").type(FinancialEntryType.INCOME).category(FinancialEntryCategory.PACKAGE_SOLD).amount(receivable.getAmount()).entryDate(Optional.ofNullable(r.date()).orElse(LocalDate.now())).status(FinancialEntryStatus.CONFIRMED).bankAccount(r.bankAccount()==null?receivable.getBankAccount():r.bankAccount()).build());receivable.setStatus("PAID");receivable.setReceivedAt(e.getEntryDate());receivable.setFinancialEntry(e);receivables.save(receivable);}
 @PostMapping("/receivables/{id}/unsettle") @Transactional public void unsettleReceivable(@PathVariable UUID id){Receivable receivable=receivables.findById(id).orElseThrow(()->new ResourceNotFoundException("recebimento não encontrado"));assertAgency(receivable.getSale());if(!"PAID".equals(receivable.getStatus()))throw new IllegalArgumentException("Recebimento não está quitado");FinancialEntry entry=receivable.getFinancialEntry();receivable.setStatus("PENDING");receivable.setReceivedAt(null);receivable.setFinancialEntry(null);receivables.save(receivable);if(entry!=null)financialEntries.delete(entry);}
 @PatchMapping("/receivables/{id}") @Transactional public void updateReceivable(@PathVariable UUID id,@RequestBody UpdateReceivable r){Receivable receivable=receivables.findById(id).orElseThrow(()->new ResourceNotFoundException("recebimento não encontrado"));assertAgency(receivable.getSale());if("PAID".equals(receivable.getStatus()))throw new IllegalArgumentException("Não é possível editar um recebimento já quitado; estorne antes.");if(r.amount()!=null)receivable.setAmount(r.amount());if(r.dueDate()!=null)receivable.setDueDate(r.dueDate());if(r.paymentMethod()!=null)receivable.setPaymentMethod(r.paymentMethod().isBlank()?null:r.paymentMethod().strip());if(r.bankAccount()!=null)receivable.setBankAccount(r.bankAccount().isBlank()?null:r.bankAccount().strip());receivables.save(receivable);}
 @DeleteMapping("/receivables/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional public void deleteReceivable(@PathVariable UUID id){Receivable receivable=receivables.findById(id).orElseThrow(()->new ResourceNotFoundException("recebimento não encontrado"));assertAgency(receivable.getSale());if("PAID".equals(receivable.getStatus()))throw new IllegalArgumentException("Não é possível excluir um recebimento já quitado; estorne antes.");receivables.delete(receivable);}
 @PostMapping("/payables/{id}/settle") @Transactional public void settlePayable(@PathVariable UUID id,@RequestBody Settle r){Payable payable=payables.findById(id).orElseThrow(()->new ResourceNotFoundException("pagamento não encontrado"));assertAgency(payable.getSale());if("PAID".equals(payable.getStatus()))throw new IllegalArgumentException("Pagamento já quitado");FinancialEntry e=financialEntries.save(FinancialEntry.builder().agency(payable.getSale().getAgency()).supplier(payable.getSupplier()).description("Pagamento de "+payable.getPayableType()).type(FinancialEntryType.EXPENSE).category("COMMISSION".equals(payable.getPayableType())?FinancialEntryCategory.COMMISSION:FinancialEntryCategory.OTHER).amount(payable.getAmount()).entryDate(Optional.ofNullable(r.date()).orElse(LocalDate.now())).status(FinancialEntryStatus.CONFIRMED).bankAccount(r.bankAccount()).build());payable.setStatus("PAID");payable.setPaidAt(e.getEntryDate());payable.setFinancialEntry(e);payables.save(payable);}

 /** Lista plana de recebíveis da agência (todas as vendas), com filtros — alimenta as telas Receitas e Vendas. */
 @GetMapping("/receivables") @Transactional public List<ReceivableRow> listReceivables(@RequestParam(required=false) UUID customerId,@RequestParam(required=false) String status,@RequestParam(required=false) LocalDate dueFrom,@RequestParam(required=false) LocalDate dueTo,@RequestParam(required=false) LocalDate paidFrom,@RequestParam(required=false) LocalDate paidTo){
  UUID a=TenantContext.requireAgencyId();
  List<Receivable> all=receivables.findBySale_Agency_IdOrderByDueDateDesc(a);
  Map<UUID,Long> countBySale=all.stream().collect(Collectors.groupingBy(r->r.getSale().getId(),Collectors.counting()));
  List<UUID> saleIds=all.stream().map(r->r.getSale().getId()).distinct().toList();
  Map<UUID,String> tagBySale=saleIds.isEmpty()?Map.of():items.findBySale_IdInOrderByDescriptionAsc(saleIds).stream().collect(Collectors.toMap(i->i.getSale().getId(),SaleItem::getDescription,(x,y)->x));
  return all.stream()
   .filter(r->customerId==null||customerId.equals(r.getSale().getCustomer().getId()))
   .filter(r->status==null||status.isBlank()||status.equalsIgnoreCase(r.getStatus()))
   .filter(r->dueFrom==null||!r.getDueDate().isBefore(dueFrom))
   .filter(r->dueTo==null||!r.getDueDate().isAfter(dueTo))
   .filter(r->paidFrom==null||(r.getReceivedAt()!=null&&!r.getReceivedAt().isBefore(paidFrom)))
   .filter(r->paidTo==null||(r.getReceivedAt()!=null&&!r.getReceivedAt().isAfter(paidTo)))
   .map(r->ReceivableRow.from(r,countBySale.getOrDefault(r.getSale().getId(),0L).intValue(),tagBySale.get(r.getSale().getId())))
   .toList();
 }

 private Sale find(UUID id){return sales.findByIdAndAgency_Id(id,TenantContext.requireAgencyId()).orElseThrow(()->new ResourceNotFoundException("venda não encontrada"));} private Supplier supplier(UUID id,UUID a){return id==null?null:suppliers.findByIdAndAgency_Id(id,a).orElseThrow(()->new ResourceNotFoundException("fornecedor não encontrado"));} private void assertAgency(Sale sale){if(!TenantContext.requireAgencyId().equals(sale.getAgency().getId()))throw new ResourceNotFoundException("registro não encontrado");} private static <T> List<T> safe(List<T> list){return list==null?List.of():list;} private static String blankOr(String value,String fallback){return value==null||value.isBlank()?fallback:value.strip();}
 private static BigDecimal commissionAmount(Commission c,BigDecimal total){if(c.calculationValue().signum()<0)throw new IllegalArgumentException("Comissão inválida");return "PERCENTAGE".equals(c.calculationType())?total.multiply(c.calculationValue()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP):c.calculationValue();}
 private static void validateTotals(CreateSale r){BigDecimal receive=safe(r.receivables()).stream().map(Installment::amount).reduce(ZERO,BigDecimal::add);BigDecimal direct=safe(r.items()).stream().filter(i->Boolean.TRUE.equals(i.customerPaysSupplierDirectly())).map(Item::saleAmount).reduce(ZERO,BigDecimal::add);if(receive.add(direct).compareTo(r.totalAmount())!=0)throw new IllegalArgumentException("Parcelas e valores pagos direto ao fornecedor devem somar o valor total da venda");}
 public record CreateSale(@NotNull UUID customerId,UUID quotationId,@NotNull @DecimalMin("0.01") BigDecimal totalAmount,@NotNull LocalDate saleDate,String recurrenceFrequency,String notes,List<@Valid Item> items,List<@Valid Installment> receivables,List<@Valid Commission> commissions){} public record Item(UUID supplierId,@NotNull String description,String itemType,@NotNull @DecimalMin("0.00") BigDecimal saleAmount,@DecimalMin("0.00") BigDecimal supplierCost,Boolean customerPaysSupplierDirectly,LocalDate dueDate){} public record Installment(@NotNull Integer number,@NotNull @DecimalMin("0.01") BigDecimal amount,@NotNull LocalDate dueDate,String paymentMethod,String bankAccount){} public record Commission(@NotNull UUID recipientUserId,@NotNull String calculationType,@NotNull @DecimalMin("0.00") BigDecimal calculationValue,LocalDate dueDate){} public record Settle(String bankAccount,LocalDate date){}
 public record SaleSummary(UUID id,UUID customerId,String customerName,BigDecimal totalAmount,LocalDate saleDate,String status){static SaleSummary from(Sale s){return new SaleSummary(s.getId(),s.getCustomer().getId(),s.getCustomer().getName(),s.getTotalAmount(),s.getSaleDate(),s.getStatus());}}
 public record SaleDetails(SaleSummary sale,List<ItemResponse> items,List<ReceivableResponse> receivables,List<PayableResponse> payables,List<CommissionResponse> commissions,BigDecimal supplierCosts,BigDecimal commissionsTotal,BigDecimal grossProfit,BigDecimal netProfit){static SaleDetails from(Sale s,List<SaleItem> i,List<Receivable> r,List<Payable> p,List<SaleCommission> c){BigDecimal costs=i.stream().map(SaleItem::getSupplierCost).filter(Objects::nonNull).reduce(ZERO,BigDecimal::add);BigDecimal comm=c.stream().map(SaleCommission::getAmount).reduce(ZERO,BigDecimal::add);return new SaleDetails(SaleSummary.from(s),i.stream().map(ItemResponse::from).toList(),r.stream().map(ReceivableResponse::from).toList(),p.stream().map(PayableResponse::from).toList(),c.stream().map(CommissionResponse::from).toList(),costs,comm,s.getTotalAmount().subtract(costs),s.getTotalAmount().subtract(costs).subtract(comm));}}
 public record ItemResponse(UUID id,String description,String itemType,BigDecimal saleAmount,BigDecimal supplierCost,boolean customerPaysSupplierDirectly,UUID supplierId,String supplierName){static ItemResponse from(SaleItem i){return new ItemResponse(i.getId(),i.getDescription(),i.getItemType(),i.getSaleAmount(),i.getSupplierCost(),Boolean.TRUE.equals(i.getCustomerPaysSupplierDirectly()),i.getSupplier()==null?null:i.getSupplier().getId(),i.getSupplier()==null?null:i.getSupplier().getName());}} public record ReceivableResponse(UUID id,Integer installmentNumber,BigDecimal amount,LocalDate dueDate,String status){static ReceivableResponse from(Receivable r){return new ReceivableResponse(r.getId(),r.getInstallmentNumber(),r.getAmount(),r.getDueDate(),r.getStatus());}} public record PayableResponse(UUID id,String payableType,BigDecimal amount,LocalDate dueDate,String status,String supplierName,String recipientName){static PayableResponse from(Payable p){return new PayableResponse(p.getId(),p.getPayableType(),p.getAmount(),p.getDueDate(),p.getStatus(),p.getSupplier()==null?null:p.getSupplier().getName(),p.getCommissionRecipientUser()==null?null:p.getCommissionRecipientUser().getName());}} public record CommissionResponse(UUID id,UUID recipientUserId,String recipientName,String calculationType,BigDecimal calculationValue,BigDecimal amount){static CommissionResponse from(SaleCommission c){return new CommissionResponse(c.getId(),c.getRecipientUser().getId(),c.getRecipientUser().getName(),c.getCalculationType(),c.getCalculationValue(),c.getAmount());}}
 public record UpdateReceivable(BigDecimal amount,LocalDate dueDate,String paymentMethod,String bankAccount){}
 public record ReceivableRow(UUID id,UUID saleId,UUID customerId,String customerName,String notes,String itemTag,String paymentMethod,String bankAccount,LocalDate dueDate,LocalDate receivedAt,BigDecimal amount,String status,Integer installmentNumber,Integer installmentsTotal){static ReceivableRow from(Receivable r,int total,String tag){Sale s=r.getSale();return new ReceivableRow(r.getId(),s.getId(),s.getCustomer().getId(),s.getCustomer().getName(),s.getNotes(),tag,r.getPaymentMethod(),r.getBankAccount(),r.getDueDate(),r.getReceivedAt(),r.getAmount(),r.getStatus(),r.getInstallmentNumber(),total);}}
 public record MyCommission(UUID payableId,UUID saleId,UUID customerId,String customerName,LocalDate saleDate,BigDecimal amount,LocalDate dueDate,String status,LocalDate paidAt){static MyCommission from(Payable p){return new MyCommission(p.getId(),p.getSale().getId(),p.getSale().getCustomer().getId(),p.getSale().getCustomer().getName(),p.getSale().getSaleDate(),p.getAmount(),p.getDueDate(),p.getStatus(),p.getPaidAt());}}
}
