ALTER TABLE agencies ADD COLUMN IF NOT EXISTS deletion_scheduled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE agencies ADD COLUMN IF NOT EXISTS status_before_deletion VARCHAR(32);
ALTER TABLE users ALTER COLUMN agency_id DROP NOT NULL;
